services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: always


  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin  # Adding container name for easier reference
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@example.com
        - PGADMIN_DEFAULT_PASSWORD=admin
        - PGADMIN_CONFIG_SERVER_MODE=False
      ports:
        - "5050:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
        - ./servers.json:/pgadmin4/servers.json
      depends_on:
        postgres:
          condition: service_healthy
      restart: always

  airflow-webserver:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY='_awsOQoMRT0CDl-k0rEa9XPRnrtq_L13iZ-0skryIkg='
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false  # Changed to false to automatically enable DAGs
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health || exit 0"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s
    restart: always

  airflow-scheduler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY='_awsOQoMRT0CDl-k0rEa9XPRnrtq_L13iZ-0skryIkg='
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false  # Changed to false to automatically enable DAGs
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname) || exit 0"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: always

  airflow-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY='_awsOQoMRT0CDl-k0rEa9XPRnrtq_L13iZ-0skryIkg='
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false  # Changed to false to automatically enable DAGs
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW_HOME=/opt/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: version
    restart: on-failure

  # New service that triggers the health check DAG after all services are running
  airflow-trigger-healthcheck:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY='_awsOQoMRT0CDl-k0rEa9XPRnrtq_L13iZ-0skryIkg='
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "sleep 15 && airflow dags unpause health_check_dag && airflow dags trigger health_check_dag"
    restart: on-failure

volumes:
  postgres-db-volume:
  pgadmin-data: 